kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: helloworld-apps
  name: helloworld-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-apps
  template:     
    metadata:
      labels:
        app: helloworld-apps
    spec:
      containers:
      - name: helloworld-apps
        imagePullPolicy: Always
        image:  hellodockeracr.azurecr.io/nkrsingh/myapps:hello-docker-latest
        ports:
        - containerPort: 9080

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: helloworld-apps
  name: helloworld-apps
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 9080
 selector:
  app: helloworld-apps
