on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n mydocreg01 -g mydocreg019dd2-rg --location "North Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n mydocreg01 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n mydocreg01 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n mydocreg01 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: mydocreg01.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/hello-docker" -f  "hello-docker/Dockerfile" -t mydocreg01.azurecr.io/mycluster:${{ github.sha }}
        docker push mydocreg01.azurecr.io/mycluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_mycluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mycluster050c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mycluster050c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mycluster050c
        container-registry-url: mydocreg01.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: mycluster050c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          mydocreg01.azurecr.io/mycluster:${{ github.sha }}
        imagepullsecrets: |
          myclusterdockerauth