on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: hellodockeracr.azurecr.io
        username: ${{ secrets.acr_hellodockeracr_username }}
        password: ${{ secrets.acr_hellodockeracr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/hello-docker" -f  "hello-docker/Dockerfile" -t hellodockeracr.azurecr.io/mycluster:${{ github.sha }}
        docker push hellodockeracr.azurecr.io/mycluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mycluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mycluster6a3b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mycluster6a3b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mycluster6a3b
        container-registry-url: hellodockeracr.azurecr.io
        container-registry-username: ${{ secrets.acr_hellodockeracr_username }}
        container-registry-password: ${{ secrets.acr_hellodockeracr_password }}
        secret-name: myclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: mycluster6a3b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          hellodockeracr.azurecr.io/mycluster:${{ github.sha }}
        imagepullsecrets: |
          myclusterdockerauth